// <auto-generated />
using System;
using Actividad3.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Actividad3.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Actividad3.Domain.Entities.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<Guid>("ColonyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HealthState")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Race")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Weight")
                        .HasMaxLength(5)
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ColonyId");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Cat_Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cat_Name");

                    b.HasIndex("Race")
                        .HasDatabaseName("IX_Cat_Race");

                    b.ToTable("Cats", "DWES");
                });

            modelBuilder.Entity("Actividad3.Domain.Entities.Colony", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Image")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MobileNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TelephoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Colony_Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Colony_Name");

                    b.ToTable("Colonies", "DWES");
                });

            modelBuilder.Entity("Actividad3.Domain.Entities.ColonyPartner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColonyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ColonyId");

                    b.HasIndex("PartnerId");

                    b.ToTable("ColonyPartners", "DWES");
                });

            modelBuilder.Entity("Actividad3.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TelephoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Partner_Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Partner_Name");

                    b.ToTable("Partners", "DWES");
                });

            modelBuilder.Entity("Actividad3.Domain.Entities.Cat", b =>
                {
                    b.HasOne("Actividad3.Domain.Entities.Colony", "Colony")
                        .WithMany("CatItems")
                        .HasForeignKey("ColonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colony");
                });

            modelBuilder.Entity("Actividad3.Domain.Entities.ColonyPartner", b =>
                {
                    b.HasOne("Actividad3.Domain.Entities.Colony", "Colony")
                        .WithMany("ColonyPartnerItems")
                        .HasForeignKey("ColonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Actividad3.Domain.Entities.Partner", "Partner")
                        .WithMany("ColonyPartnerItems")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colony");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("Actividad3.Domain.Entities.Colony", b =>
                {
                    b.Navigation("CatItems");

                    b.Navigation("ColonyPartnerItems");
                });

            modelBuilder.Entity("Actividad3.Domain.Entities.Partner", b =>
                {
                    b.Navigation("ColonyPartnerItems");
                });
#pragma warning restore 612, 618
        }
    }
}
